// GENERATED by scripts/optimize-images.mjs from scripts/photo-manifest.mjs — do not edit.

export const SECTIONS = {
  "automotive": {
    "title": "Automotive",
    "items": [
      {
        "src": "./images/automotive-1.webp",
        "full": "./images/automotive-1-full.webp",
        "w": 1800,
        "h": 1200,
        "alt": "White Audi RS5 rear, warehouse",
        "chip": "FUJIFILM X-T3 · XF16-55mm F2.8 · 16mm · f/4 · 1/250s · ISO 1600",
        "camera": "FUJIFILM X-T3 · XF16-55mm F2.8",
        "settings": "16mm · f/4 · 1/250s · ISO 1600"
      },
      {
        "src": "./images/automotive-2.webp",
        "full": "./images/automotive-2-full.webp",
        "w": 1800,
        "h": 1200,
        "alt": "Green Audi RS5, rusty fence",
        "chip": "FUJIFILM X-T3 · XF56mm F1.2 · 56mm · f/4 · 1/240s · ISO 160",
        "camera": "FUJIFILM X-T3 · XF56mm F1.2",
        "settings": "56mm · f/4 · 1/240s · ISO 160"
      },
      {
        "src": "./images/automotive-3.webp",
        "full": "./images/automotive-3-full.webp",
        "w": 1800,
        "h": 1200,
        "alt": "Range Rover at dusk",
        "chip": "FUJIFILM X-T20 · XF18-55mm F2.8-4 · 55mm · f/4 · 1/250s · ISO 400",
        "camera": "FUJIFILM X-T20 · XF18-55mm F2.8-4",
        "settings": "55mm · f/4 · 1/250s · ISO 400"
      },
      {
        "src": "./images/automotive-4.webp",
        "full": "./images/automotive-4-full.webp",
        "w": 1800,
        "h": 1200,
        "alt": "Black BMW E32 in dark garage",
        "chip": "FUJIFILM X-T3 · XF56mm F1.2 · 56mm · f/1.4 · 1/160s · ISO 800",
        "camera": "FUJIFILM X-T3 · XF56mm F1.2",
        "settings": "56mm · f/1.4 · 1/160s · ISO 800"
      },
      {
        "src": "./images/automotive-5.webp",
        "full": "./images/automotive-5-full.webp",
        "w": 1800,
        "h": 1200,
        "alt": "White Audi RS5 front, warehouse",
        "chip": "FUJIFILM X-T3 · XF16-55mm F2.8 · 16mm · f/4 · 1/250s · ISO 1600",
        "camera": "FUJIFILM X-T3 · XF16-55mm F2.8",
        "settings": "16mm · f/4 · 1/250s · ISO 1600"
      },
      {
        "src": "./images/automotive-6.webp",
        "full": "./images/automotive-6-full.webp",
        "w": 1800,
        "h": 1200,
        "alt": "Neon yellow widebody BMW M3 outside modern office building",
        "chip": "FUJIFILM X-T3 · XF35mm F1.4 · 35mm · f/2 · 1/250s · ISO 640",
        "camera": "FUJIFILM X-T3 · XF35mm F1.4",
        "settings": "35mm · f/2 · 1/250s · ISO 640"
      },
      {
        "src": "./images/automotive-7.webp",
        "full": "./images/automotive-7-full.webp",
        "w": 1800,
        "h": 1200,
        "alt": "Black BMW 7 Series E32 outside industrial warehouse",
        "chip": "FUJIFILM X-T3 · XF16-55mm F2.8 · 16mm · f/4 · 1/250s · ISO 1600",
        "camera": "FUJIFILM X-T3 · XF16-55mm F2.8",
        "settings": "16mm · f/4 · 1/250s · ISO 1600"
      },
      {
        "src": "./images/automotive-8.webp",
        "full": "./images/automotive-8-full.webp",
        "w": 1800,
        "h": 1200,
        "alt": "Grey Mercedes-AMG A45 outside modern office building",
        "chip": "FUJIFILM X-T3 · XF35mm F1.4 · 35mm · f/1.4 · 1/1600s · ISO 160",
        "camera": "FUJIFILM X-T3 · XF35mm F1.4",
        "settings": "35mm · f/1.4 · 1/1600s · ISO 160"
      },
      {
        "src": "./images/automotive-9.webp",
        "full": "./images/automotive-9-full.webp",
        "w": 1800,
        "h": 1200,
        "alt": "White Ford Focus RS by industrial bridge at sunset",
        "chip": "FUJIFILM X-T3 · XF35mm F1.4 · 35mm · f/4 · 1/1100s · ISO 640",
        "camera": "FUJIFILM X-T3 · XF35mm F1.4",
        "settings": "35mm · f/4 · 1/1100s · ISO 640"
      },
      {
        "src": "./images/automotive-10.webp",
        "full": "./images/automotive-10-full.webp",
        "w": 1800,
        "h": 1200,
        "alt": "Blue Audi RS3 Sportback parked at night by K2 building",
        "chip": "FUJIFILM X-T3 · XF56mm F1.2 · 56mm · f/2 · 1/1400s · ISO 640",
        "camera": "FUJIFILM X-T3 · XF56mm F1.2",
        "settings": "56mm · f/2 · 1/1400s · ISO 640"
      },
      {
        "src": "./images/automotive-11.webp",
        "full": "./images/automotive-11-full.webp",
        "w": 1800,
        "h": 1200,
        "alt": "Black and white shot of Porsche Cayman GT4 RS on forest road",
        "chip": "FUJIFILM X-T3 · XF56mm F1.2 · 56mm · f/1.4 · 1/500s · ISO 640",
        "camera": "FUJIFILM X-T3 · XF56mm F1.2",
        "settings": "56mm · f/1.4 · 1/500s · ISO 640"
      },
      {
        "src": "./images/automotive-12.webp",
        "full": "./images/automotive-12-full.webp",
        "w": 1800,
        "h": 1200,
        "alt": "Pink and black liveried Toyota GR Yaris in the snow by a castle",
        "chip": "FUJIFILM X-T3 · XF56mm F1.2 · 56mm · f/2 · 1/1100s · ISO 640",
        "camera": "FUJIFILM X-T3 · XF56mm F1.2",
        "settings": "56mm · f/2 · 1/1100s · ISO 640"
      },
      {
        "src": "./images/automotive-13.webp",
        "full": "./images/automotive-13-full.webp",
        "w": 1800,
        "h": 1200,
        "alt": "Stanced black Seat Leon in a parking garage",
        "chip": "FUJIFILM X-T3 · XF56mm F1.2 · 56mm · f/2.8 · 1.2s · ISO 800",
        "camera": "FUJIFILM X-T3 · XF56mm F1.2",
        "settings": "56mm · f/2.8 · 1.2s · ISO 800"
      },
      {
        "src": "./images/automotive-14.webp",
        "full": "./images/automotive-14-full.webp",
        "w": 1800,
        "h": 1201,
        "alt": "Black Subaru WRX STI inside an industrial workshop",
        "chip": "LEICA Q2 · SUMMILUX 28mm F1.7 · 28mm · f/1.7 · 1/1000s · ISO 100",
        "camera": "LEICA Q2 · SUMMILUX 28mm F1.7",
        "settings": "28mm · f/1.7 · 1/1000s · ISO 100"
      }
    ]
  },
  "portraits": {
    "title": "Portraits",
    "items": [
      {
        "src": "./images/portrait-1.webp",
        "full": "./images/portrait-1-full.webp",
        "w": 1200,
        "h": 801,
        "alt": "Portrait, woman on stone stairs in white corset",
        "caption": "On the steps, quiet composure in white."
      },
      {
        "src": "./images/portrait-2.webp",
        "full": "./images/portrait-2-full.webp",
        "w": 1200,
        "h": 1800,
        "alt": "Portrait with off-shoulder white shirt",
        "caption": "Off-shoulder white, soft natural light."
      },
      {
        "src": "./images/portrait-3.webp",
        "full": "./images/portrait-3-full.webp",
        "w": 1200,
        "h": 800,
        "alt": "Close-up portrait against teal wall",
        "caption": "Close study against teal, editorial mood."
      },
      {
        "src": "./images/portrait-4.webp",
        "full": "./images/portrait-4-full.webp",
        "w": 1200,
        "h": 1800,
        "alt": "Portrait in metallic dress by fence",
        "caption": "Metallic dress against a weathered fence."
      },
      {
        "src": "./images/portrait-5.webp",
        "full": "./images/portrait-5-full.webp",
        "w": 1200,
        "h": 801,
        "alt": "Portrait, dramatic shadow across face",
        "caption": "Dramatic shadow play across the face."
      },
      {
        "src": "./images/portrait-6.webp",
        "full": "./images/portrait-6-full.webp",
        "w": 1200,
        "h": 1800,
        "alt": "Portrait sitting on wooden floor in white shirt",
        "caption": "Seated in natural light, relaxed portrait."
      },
      {
        "src": "./images/portrait-7.webp",
        "full": "./images/portrait-7-full.webp",
        "w": 1200,
        "h": 1800,
        "alt": "Portrait on a pier boardwalk",
        "caption": "On the boardwalk, golden hour."
      },
      {
        "src": "./images/portrait-8.webp",
        "full": "./images/portrait-8-full.webp",
        "w": 1200,
        "h": 800,
        "alt": "Portrait in silver dress, garden backdrop",
        "caption": "Silver dress, soft green backdrop."
      },
      {
        "src": "./images/portrait-9.webp",
        "full": "./images/portrait-9-full.webp",
        "w": 1200,
        "h": 800,
        "alt": "Portrait in white lace top inside a garage",
        "caption": "White lace, workshop backdrop."
      },
      {
        "src": "./images/portrait-10.webp",
        "full": "./images/portrait-10-full.webp",
        "w": 1200,
        "h": 1800,
        "alt": "Black and white portrait in pleated skirt outdoors",
        "caption": "Monochrome, open field at dusk."
      },
      {
        "src": "./images/portrait-11.webp",
        "full": "./images/portrait-11-full.webp",
        "w": 1200,
        "h": 1800,
        "alt": "Kinetic water sculpture with model out of focus",
        "caption": "Kinetic fountain, layered depth of field."
      },
      {
        "src": "./images/portrait-12.webp",
        "full": "./images/portrait-12-full.webp",
        "w": 1200,
        "h": 1800,
        "alt": "Portrait in metallic dress beside water sculpture",
        "caption": "Metallic dress, industrial fountain backdrop."
      },
      {
        "src": "./images/portrait-13.webp",
        "full": "./images/portrait-13-full.webp",
        "w": 1200,
        "h": 1800,
        "alt": "Portrait leaning against wire mesh wall",
        "caption": "Leaning into the frame, wire mesh texture."
      },
      {
        "src": "./images/portrait-14.webp",
        "full": "./images/portrait-14-full.webp",
        "w": 1200,
        "h": 1800,
        "alt": "Portrait with arms raised, fountain sculpture behind",
        "caption": "Arms raised, tattoo detail in soft light."
      },
      {
        "src": "./images/portrait-15.webp",
        "full": "./images/portrait-15-full.webp",
        "w": 1200,
        "h": 1800,
        "alt": "Portrait against greenery, hand in hair",
        "caption": "Green backdrop, quiet upward gaze."
      },
      {
        "src": "./images/portrait-16.webp",
        "full": "./images/portrait-16-full.webp",
        "w": 1200,
        "h": 1800,
        "alt": "Portrait inside a car, seatbelt across frame",
        "caption": "In the car, candid and unposed."
      },
      {
        "src": "./images/portrait-17.webp",
        "full": "./images/portrait-17-full.webp",
        "w": 1200,
        "h": 1800,
        "alt": "Portrait in trench coat against garage door",
        "caption": "Trench coat, evening light on steel."
      }
    ]
  },
  "automotive-portraits": {
    "title": "Cars & People",
    "items": [
      {
        "src": "./images/cars-1.webp",
        "full": "./images/cars-1-full.webp",
        "w": 1200,
        "h": 800,
        "alt": "Blue BMW M2 drifting through smoke on a forest road",
        "caption": "Blue M2, sideways through the smoke."
      },
      {
        "src": "./images/cars-2.webp",
        "full": "./images/cars-2-full.webp",
        "w": 1200,
        "h": 800,
        "alt": "Portrait in pink tracksuit with green Audi RS5",
        "caption": "Pink tracksuit against a green RS5."
      },
      {
        "src": "./images/cars-3.webp",
        "full": "./images/cars-3-full.webp",
        "w": 1200,
        "h": 800,
        "alt": "Portrait with green Audi RS5",
        "caption": "Studio-style portrait beside the green RS5."
      },
      {
        "src": "./images/cars-4.webp",
        "full": "./images/cars-4-full.webp",
        "w": 1200,
        "h": 800,
        "alt": "Woman leaning against green Audi RS5 by rusty gate",
        "caption": "Wide jeans, weathered gate, green RS5."
      },
      {
        "src": "./images/cars-5.webp",
        "full": "./images/cars-5-full.webp",
        "w": 1200,
        "h": 800,
        "alt": "Woman kneeling in smoke beside red Audi S3 in studio",
        "caption": "Studio smoke, red Audi S3."
      },
      {
        "src": "./images/cars-6.webp",
        "full": "./images/cars-6-full.webp",
        "w": 1200,
        "h": 1801,
        "alt": "Woman sitting against black BMW in a warehouse",
        "caption": "Seated against the E32, warehouse light."
      },
      {
        "src": "./images/cars-7.webp",
        "full": "./images/cars-7-full.webp",
        "w": 1200,
        "h": 800,
        "alt": "Woman watching a black Seat Leon with hood open",
        "caption": "Engine bay reveal, Seat Leon."
      },
      {
        "src": "./images/cars-8.webp",
        "full": "./images/cars-8-full.webp",
        "w": 1200,
        "h": 1800,
        "alt": "Woman in red fur coat, black car in background",
        "caption": "Red fur, city parking lot."
      },
      {
        "src": "./images/cars-9.webp",
        "full": "./images/cars-9-full.webp",
        "w": 1200,
        "h": 800,
        "alt": "Woman in red fur coat leaning on black car",
        "caption": "Leaning on the spoiler, bold red fur."
      },
      {
        "src": "./images/cars-10.webp",
        "full": "./images/cars-10-full.webp",
        "w": 1200,
        "h": 1800,
        "alt": "Woman in pink hat watching pink Toyota GR Yaris in snow",
        "caption": "Snow day, pink GR Yaris."
      },
      {
        "src": "./images/cars-11.webp",
        "full": "./images/cars-11-full.webp",
        "w": 1200,
        "h": 800,
        "alt": "Man leaning against a booth beside a blue Audi RS3 at night",
        "caption": "Night shift, blue Audi RS3."
      },
      {
        "src": "./images/cars-12.webp",
        "full": "./images/cars-12-full.webp",
        "w": 1200,
        "h": 1800,
        "alt": "Legs in red heels stepping out of a classic car",
        "caption": "Red heels, open door detail."
      },
      {
        "src": "./images/cars-13.webp",
        "full": "./images/cars-13-full.webp",
        "w": 1200,
        "h": 1800,
        "alt": "Black and white portrait, woman in tulle dress against Mercedes",
        "caption": "Monochrome, tulle against the Mercedes."
      },
      {
        "src": "./images/cars-14.webp",
        "full": "./images/cars-14-full.webp",
        "w": 1200,
        "h": 1801,
        "alt": "Woman in Let's Save V8 shirt beside a green BMW M3",
        "caption": "Let's Save V8, green M3 headlight glow."
      },
      {
        "src": "./images/cars-15.webp",
        "full": "./images/cars-15-full.webp",
        "w": 1200,
        "h": 1800,
        "alt": "Woman leaning on green BMW M3 hood, neon garage ceiling",
        "caption": "Leaning on the hood, honeycomb light."
      }
    ]
  },
  "products": {
    "title": "Products",
    "items": [
      {
        "src": "./images/product-1.webp",
        "full": "./images/product-1-full.webp",
        "w": 1200,
        "h": 799,
        "alt": "Aluminum profile close-up on BYLD production line"
      },
      {
        "src": "./images/product-2.webp",
        "full": "./images/product-2-full.webp",
        "w": 1200,
        "h": 800,
        "alt": "BYLD press tooling detail"
      },
      {
        "src": "./images/product-3.webp",
        "full": "./images/product-3-full.webp",
        "w": 1200,
        "h": 800,
        "alt": "BYLD facility corridor with signage"
      },
      {
        "src": "./images/product-4.webp",
        "full": "./images/product-4-full.webp",
        "w": 1200,
        "h": 1800,
        "alt": "BYLD WALLE machine control panel"
      },
      {
        "src": "./images/product-5.webp",
        "full": "./images/product-5-full.webp",
        "w": 1200,
        "h": 800,
        "alt": "BYLD production hall entrance"
      },
      {
        "src": "./images/product-6.webp",
        "full": "./images/product-6-full.webp",
        "w": 1200,
        "h": 1800,
        "alt": "Black folding knife, blade open against dark wood background"
      },
      {
        "src": "./images/product-7.webp",
        "full": "./images/product-7-full.webp",
        "w": 1200,
        "h": 1800,
        "alt": "Black folding knife closed, dark moody lighting"
      },
      {
        "src": "./images/product-8.webp",
        "full": "./images/product-8-full.webp",
        "w": 1200,
        "h": 1800,
        "alt": "Leica camera resting in its box, overhead view"
      },
      {
        "src": "./images/product-9.webp",
        "full": "./images/product-9-full.webp",
        "w": 1200,
        "h": 1800,
        "alt": "Leica lens macro detail, aperture and focus rings"
      },
      {
        "src": "./images/product-10.webp",
        "full": "./images/product-10-full.webp",
        "w": 1200,
        "h": 1800,
        "alt": "Leica camera and lens packed in presentation box"
      },
      {
        "src": "./images/product-11.webp",
        "full": "./images/product-11-full.webp",
        "w": 1200,
        "h": 1800,
        "alt": "Gold ring with black onyx stone on textured fabric"
      },
      {
        "src": "./images/product-12.webp",
        "full": "./images/product-12-full.webp",
        "w": 1200,
        "h": 1800,
        "alt": "Gold and onyx ring held close, shallow depth of field"
      },
      {
        "src": "./images/product-13.webp",
        "full": "./images/product-13-full.webp",
        "w": 1200,
        "h": 800,
        "alt": "White BMW 1 Series, front wheel and splitter detail"
      },
      {
        "src": "./images/product-14.webp",
        "full": "./images/product-14-full.webp",
        "w": 1200,
        "h": 1800,
        "alt": "White BMW 1 Series rear wheel close-up, brick backdrop"
      },
      {
        "src": "./images/product-15.webp",
        "full": "./images/product-15-full.webp",
        "w": 1200,
        "h": 1800,
        "alt": "Hands breaking open a blueberry pastry"
      }
    ]
  },
  "pets": {
    "title": "Pets",
    "items": [
      {
        "src": "./images/pets-1.webp",
        "full": "./images/pets-1-full.webp",
        "w": 1200,
        "h": 1800,
        "alt": "Cream British Shorthair cat resting paws on white shelf, Rebel poster behind"
      },
      {
        "src": "./images/pets-2.webp",
        "full": "./images/pets-2-full.webp",
        "w": 1200,
        "h": 800,
        "alt": "Cream cat looking up from white shelf, overhead view"
      },
      {
        "src": "./images/pets-3.webp",
        "full": "./images/pets-3-full.webp",
        "w": 1200,
        "h": 1800,
        "alt": "Cream cat with grumpy expression on shelf"
      },
      {
        "src": "./images/pets-4.webp",
        "full": "./images/pets-4-full.webp",
        "w": 1200,
        "h": 1800,
        "alt": "Black cocker spaniel looking up at golden hour, tongue out"
      },
      {
        "src": "./images/pets-5.webp",
        "full": "./images/pets-5-full.webp",
        "w": 1200,
        "h": 800,
        "alt": "Black cocker spaniel meeting another dog through a fence"
      },
      {
        "src": "./images/pets-6.webp",
        "full": "./images/pets-6-full.webp",
        "w": 1200,
        "h": 800,
        "alt": "Black cocker spaniel close-up portrait in a field, tongue out"
      },
      {
        "src": "./images/pets-7.webp",
        "full": "./images/pets-7-full.webp",
        "w": 1200,
        "h": 800,
        "alt": "Cream cat resting head on paws, low angle indoors"
      },
      {
        "src": "./images/pets-8.webp",
        "full": "./images/pets-8-full.webp",
        "w": 1200,
        "h": 1800,
        "alt": "Cream cat looking up from the floor, overhead view"
      }
    ]
  }
};

export const SECTION_ORDER = ["automotive","portraits","automotive-portraits","products","pets"];

export default SECTIONS;
